# CS 577 Homework 1
#### Anas Puthawala

In [348]:
import numpy as np
import scipy
import sympy

## Part A

In [358]:
A = np.array([1,2,3])
A = np.reshape(A, newshape=(3,1))

B = np.reshape(np.array([4,5,6]), newshape=(3,1))

C = np.reshape(np.array([-1, 1, 3]), newshape=(3,1))

In [359]:
A

array([[1],
       [2],
       [3]])

In [360]:
B

array([[4],
       [5],
       [6]])

In [361]:
C

array([[-1],
       [ 1],
       [ 3]])

1.

In [362]:
2*A - B

array([[-2],
       [-1],
       [ 0]])

2.

In [363]:
A_hat = A / np.linalg.norm(A)
print(f'A_hat:\n{A_hat}')

A_hat:
[[0.26726124]
 [0.53452248]
 [0.80178373]]


3.

In [364]:
np.linalg.norm(A)

3.7416573867739413

4.

In [365]:
a_1 = A[0] / np.linalg.norm(A)
a_2 = A[1] / np.linalg.norm(A)
a_3 = A[2] / np.linalg.norm(A)

print(f'Directions cosines for A: {a_1, a_2, a_3}')

Directions cosines for A: (array([0.26726124]), array([0.53452248]), array([0.80178373]))


5.

In [366]:
np.linalg.norm(B)

8.774964387392123

In [367]:
dot = np.sum(A*B)
norms = np.linalg.norm(A) * np.linalg.norm(B)

print(f'Angle between A and B in degrees: {np.rad2deg(np.arccos(np.clip(dot/norms, -1, 1)))}')

Angle between A and B in degrees: 12.933154491899135


6.

In [368]:
print(f'A•B: {np.dot(np.squeeze(A), np.squeeze(B))}\nB•A: {np.dot(np.squeeze(B), np.squeeze(A))}')

A•B: 32
B•A: 32


7.

In [369]:
costheta = dot/norms # from up above
print(f'A•B using angle between A and B: {np.linalg.norm(A) * np.linalg.norm(B) * costheta}')

A•B using angle between A and B: 32.0


8.

In [370]:
np.dot(np.squeeze(B), np.squeeze(A_hat)) / np.linalg.norm(A_hat)

8.55235974119758

9.

In [371]:
# To find a perpeinduclar vector just take the cross product
perp_vect = np.cross(np.squeeze(A), [1,0,0])
print(perp_vect)

#We can check and ensure it's perpendicular by taking the dot product
np.dot(np.squeeze(A), perp_vect)==0

[ 0  3 -2]


True

10.

In [372]:
print(f'AxB: {np.cross(np.squeeze(A), np.squeeze(B))}\nBxA: {np.cross(np.squeeze(B), np.squeeze(A))}')

AxB: [-3  6 -3]
BxA: [ 3 -6  3]


11.

In [373]:
# To find a vector that is perpendicular to both A and B we must
# Take the cross product of of Vectors A and B. The vector returned will be
# perpendicular to both A and B
perp_vector_AB = np.cross(np.squeeze(A), np.squeeze(B))
print(perp_vector_AB)

#Verify that this is indeed perpendicular to both A and B by taking the dot products
[np.dot(np.squeeze(A), perp_vector_AB)==0,
np.dot(np.squeeze(B), perp_vector_AB)==0]

[-3  6 -3]


[True, True]

12.

In [374]:
combined_matrix = np.array(([1,2,3],[4,5,6],[-1,1,3])).T
_, indexes = sympy.Matrix(combined_matrix).rref()
print(f'Indices of pivot columns: {indexes}')
print(f'Linearly dependent columns: \n{combined_matrix[:,indexes]}')


Indices of pivot columns: (0, 1)
Linearly dependent columns: 
[[1 4]
 [2 5]
 [3 6]]


A and B are linearly dependent (as they're pivot columns), C is linearly independent.

13.

In [375]:
print(f'ATb = {np.matmul(np.squeeze(A.T), np.squeeze(B))}')

#abT:
print(f'AbT = \n{np.matmul(A, B.T)}')

ATb = 32
AbT = 
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## Part B

In [376]:
A = np.array(([1,2,3], [4,-2,3], [0,5,-1]))
B = np.array(([1,2,1], [2,1,-4], [3,-2,1]))
C = np.array(([1,2,3], [4,5,6], [-1,1,3]))
D = np.array(([1,2,3]))
print(f'A: {A}\nShape: {np.shape(A)}\n')
print(f'B: {B}\nShape: {np.shape(B)}\n')
print(f'C: {C}\nShape: {np.shape(C)}\n')
print(f'D: {D}\nShape: {np.shape(D)}\n')

A: [[ 1  2  3]
 [ 4 -2  3]
 [ 0  5 -1]]
Shape: (3, 3)

B: [[ 1  2  1]
 [ 2  1 -4]
 [ 3 -2  1]]
Shape: (3, 3)

C: [[ 1  2  3]
 [ 4  5  6]
 [-1  1  3]]
Shape: (3, 3)

D: [1 2 3]
Shape: (3,)



1.

In [377]:
2*A - B

array([[ 1,  2,  5],
       [ 6, -5, 10],
       [-3, 12, -3]])

2.

In [378]:
print(f'AB: {np.matmul(A,B)}\n')
print(f'BA: {np.matmul(B,A)}')


AB: [[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]

BA: [[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


3.

In [379]:
print(f'(AB)T: {np.matmul(A,B).T}\n')
print(f'BTAT: {np.matmul(B.T, A.T)}')

(AB)T: [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]

BTAT: [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


4.

In [380]:
print(f'|A|: {np.linalg.det(A)}')
print(f'|C|: {np.linalg.det(C)}')

|A|: 54.999999999999964
|C|: 0.0


5.

In [381]:
np.shape(A)

(3, 3)

In [382]:
def orthogonal_set(A:np.ndarray, B:np.ndarray, C:np.ndarray) -> np.ndarray:
    '''This function will return the matrix of which the row vectors form an orthogonal set'''
    
    if np.dot(A[0], A[1]) == 0 or np.dot(A[0], A[2]) == 0 or np.dot(A[1], A[2]) == 0:
        return A
    elif np.dot(B[0], B[1]) == 0 or np.dot(B[0], B[2]) == 0 or np.dot(B[1], B[2]) == 0:
        return B
    elif np.dot(C[0], C[1]) == 0 or np.dot(C[0], C[2]) == 0 or np.dot(C[1], C[2]) == 0:
        return C
    

In [383]:
orthogonal_set(A, B, C)

array([[ 1,  2,  1],
       [ 2,  1, -4],
       [ 3, -2,  1]])

In [384]:
B

array([[ 1,  2,  1],
       [ 2,  1, -4],
       [ 3, -2,  1]])

Matrix B has orthogonal row vectors

6.

In [385]:
print(f'A^-1: {np.linalg.inv(A)}\n')
print(f'B^-1: {np.linalg.inv(B)}')

A^-1: [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]

B^-1: [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


7.

In [387]:
print(f'C^-1: {np.linalg.inv(C)}')

LinAlgError: Singular matrix

Since C is a singular matrix, there is no inverse.

8.

In [388]:
Ad = np.matmul(A,D)
print(Ad)

[14  9  7]


9.

In [389]:
normalized_D = D / np.linalg.norm(D)
normalized_D

array([0.26726124, 0.53452248, 0.80178373])

In [390]:
A_1 = A[0]
A_2 = A[1]
A_3 = A[2]

magnitude_D = (np.linalg.norm(D))**2

A_1d = np.dot(A_1, normalized_D)
A_2d = np.dot(A_2, normalized_D)
A_3d = np.dot(A_3, normalized_D)

Row 1, A

In [391]:
(A_1d / np.sqrt(magnitude_D))

1.0

Row 2, A

In [392]:
(A_2d / np.sqrt(magnitude_D))

0.6428571428571429

Row 3, A

In [393]:
(A_3d / np.sqrt(magnitude_D))

0.49999999999999994

10.

In [394]:
normalized_D = D / np.linalg.norm(D)
normalized_D

array([0.26726124, 0.53452248, 0.80178373])

Row 1, A

In [395]:
(np.dot(A_1, normalized_D) / magnitude_D) * normalized_D

array([0.07142857, 0.14285714, 0.21428571])

Row 2, A

In [396]:
(np.dot(A_2, normalized_D) / magnitude_D) * normalized_D

array([0.04591837, 0.09183673, 0.1377551 ])

Row 3, A

In [397]:
(np.dot(A_3, normalized_D) / magnitude_D) * normalized_D

array([0.03571429, 0.07142857, 0.10714286])

11.

In [398]:
(A_1)*D[0] + (A_2)*D[1] + (A_3)*D[2]

array([ 9, 13,  6])

12.

Bx = D

In [399]:
x = np.matmul(np.linalg.inv(B), D)
print(f'X: {x}')

X: [ 1.00000000e+00  5.55111512e-17 -2.77555756e-17]


This is basically equivalent to [1 0 0] 

13.

In [414]:
np.matmul(np.linalg.inv(C), D)

LinAlgError: Singular matrix

There is no solution x to the equation Cx=D because the matrix C is singular and therefore cannot find the inverse for that matrix.

## Part C

In [415]:
D = np.array(([1, 2], [3,2]))
E = np.array(([2, -2], [-2, 5]))
F = np.array(([1, 2], [2, 4]))

print(f'D:\n{D}\n\nE:\n{E}\n\nF:\n{F}\n')

D:
[[1 2]
 [3 2]]

E:
[[ 2 -2]
 [-2  5]]

F:
[[1 2]
 [2 4]]



1.

Note: Using np.linalg.eig normalizes the returned eigenvectors so that the norm is of unit length (i.e. 1)

In [416]:
eigenvalues_D, eigenvectors_D = np.linalg.eig(D)

print(f'Eigenvalues: \n{eigenvalues_D}')
print(f'Eigenvectors: \n{eigenvectors_D}')
print('--------')
for dim in range(np.shape(eigenvalues_D)[0]):
    print('')
    print(f'Eigenvector corresponding to Eigenvalue {eigenvalues_D[dim]} is \n{eigenvectors_D.T[dim]}\n with norm: {np.round(np.linalg.norm(eigenvectors_D.T[dim]))}')

Eigenvalues: 
[-1.  4.]
Eigenvectors: 
[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]
--------

Eigenvector corresponding to Eigenvalue -1.0 is 
[-0.70710678  0.70710678]
 with norm: 1.0

Eigenvector corresponding to Eigenvalue 4.0 is 
[-0.5547002  -0.83205029]
 with norm: 1.0


From my answer in the homework, i had that the eigenvector corresponding to eigenvalue -1 is [-1, 1] and that the eigenvector corresponding to eigenvalue 4 is [2, 3]. We can manually check and confirm this:

In [417]:
eigenvector_1 = np.array(([1,-1]))

#perform normalization
print(eigenvector_1 / np.linalg.norm(eigenvector_1))

eigenvector_4 = np.array([2,3])

#perform normalization
print(eigenvector_4/np.linalg.norm(eigenvector_4))

[ 0.70710678 -0.70710678]
[0.5547002  0.83205029]


Same values except the only difference is the sign. When np calculates the eig (using np.linalg.eig) the sign may get altered especially during normalization. we can also use sympy

In [418]:
import sympy

d = sympy.Matrix([[1,2], [3,2]])
print(f'd:\n{d}')

e = sympy.Matrix([[2,-2], [-2,5]])
print(f'e:\n{e}')

f = sympy.Matrix([[1,2], [2,4]])
print(f'f:\n{f}')

d:
Matrix([[1, 2], [3, 2]])
e:
Matrix([[2, -2], [-2, 5]])
f:
Matrix([[1, 2], [2, 4]])


In [419]:
d.eigenvects()

[(-1,
  1,
  [Matrix([
   [-1],
   [ 1]])]),
 (4,
  1,
  [Matrix([
   [2/3],
   [  1]])])]

2.

In [420]:
print(f'Dot product between eigenvectors: {np.dot(eigenvectors_D.T[0], eigenvectors_D.T[1])}')

Dot product between eigenvectors: -0.19611613513818388


3.

In [421]:
sympy.Matrix([[2,-2], [-2,5]]).eigenvects()

[(1,
  1,
  [Matrix([
   [2],
   [1]])]),
 (6,
  1,
  [Matrix([
   [-1/2],
   [   1]])])]

In [422]:
eigenvalues_E, eigenvectors_E = np.linalg.eig(E)
print(f'Eigenvalues of E: \n{eigenvalues_E}')
print(f'Eigenvectors of E: \n{eigenvectors_E}')


print(f'Dot product between eigenvectors: {np.dot(eigenvectors_E.T[0], eigenvectors_E.T[1])}')

Eigenvalues of E: 
[1. 6.]
Eigenvectors of E: 
[[-0.89442719  0.4472136 ]
 [-0.4472136  -0.89442719]]
Dot product between eigenvectors: 0.0


4.

In [423]:
E.T == E

array([[ True,  True],
       [ True,  True]])

E Transpose is equivalent to E, it's a symmetric (hermitian) matrix and therefore the eigenvectors are orthogonal and hence the dot product between the eigenvectors will be 0.

5.

In [424]:
np.linalg.lstsq(F, np.zeros((F.shape[0],1)))[0]

/var/folders/rf/k8mctbjd57n99_khq2tj1q480000gn/T/ipykernel_5873/4134326771.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(F, np.zeros((F.shape[0],1)))[0]


array([[0.],
       [0.]])

[0,0] is a trivial solution

6.

In [425]:
np.linalg.lstsq(F, np.zeros((F.shape[0],1), dtype=np.float))

/var/folders/rf/k8mctbjd57n99_khq2tj1q480000gn/T/ipykernel_5873/238139554.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.linalg.lstsq(F, np.zeros((F.shape[0],1), dtype=np.float))
/var/folders/rf/k8mctbjd57n99_khq2tj1q480000gn/T/ipykernel_5873/238139554.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(F, np.zeros((F.shape[0],1), dtype=np.float))


(array([[0.],
        [0.]]),
 array([], dtype=float64),
 1,
 array([5.00000000e+00, 1.98602732e-16]))

The trivial solution is [0,0]

7.

In [426]:
np.linalg.lstsq(D, np.zeros((D.shape[0],1), dtype=np.float))

/var/folders/rf/k8mctbjd57n99_khq2tj1q480000gn/T/ipykernel_5873/3588471221.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.linalg.lstsq(D, np.zeros((D.shape[0],1), dtype=np.float))
/var/folders/rf/k8mctbjd57n99_khq2tj1q480000gn/T/ipykernel_5873/3588471221.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(D, np.zeros((D.shape[0],1), dtype=np.float))


(array([[0.],
        [0.]]),
 array([], dtype=float64),
 2,
 array([4.13064859, 0.96837093]))

In [427]:
np.linalg.solve(D, np.zeros(shape=(np.shape(D)[0], 1)))

array([[0.],
       [0.]])

Need to check linear dependency of the rows of D

In [428]:
_, indexes = sympy.Matrix(D).T.rref()
print(indexes)

(0, 1)


In [429]:
print(D[indexes,:])

[[1 2]
 [3 2]]


According to the documentation of sympy.Matrix (https://www.geeksforgeeks.org/python-sympy-matrix-rref-method/) this also helps

the rref module of sympy matrix returns two things: The first is the reduced row echelon form, and the second is a tuple of indices of the pivot columns. The tuple of indices of the pivot columns (i.e. linearly independence). See the following https://math.stackexchange.com/questions/2577895/pivots-and-linear-independence to get a better understanding of linear independence and how pivots relate.

Finally, since all the columns are pivot columns then we can say that they're linearly independent and that the only solution to Dx=0 is x=0. (see: https://web.mit.edu/14.102/www/notes/lecturenotes0916.pdf)

In [438]:
np.linalg.norm(np.array(([1/14,2/14,3/14])))

0.2672612419124244