# CS 577 Homework 1
#### Anas Puthawala

In [1]:
import numpy as np
import scipy

## Part A

In [30]:
A = np.array([1,2,3])
A = np.reshape(A, newshape=(3,1))

B = np.reshape(np.array([4,5,6]), newshape=(3,1))

C = np.reshape(np.array([-1, 1, 3]), newshape=(3,1))

In [31]:
A

array([[1],
       [2],
       [3]])

In [32]:
B

array([[4],
       [5],
       [6]])

In [33]:
C

array([[-1],
       [ 1],
       [ 3]])

1.

In [37]:
2*A - B

array([[-2],
       [-1],
       [ 0]])

2.

In [79]:
A_hat = A / np.linalg.norm(A)
print(f'A_hat:\n{A_hat}')

A_hat:
[[0.26726124]
 [0.53452248]
 [0.80178373]]


3.

In [39]:
np.linalg.norm(A)

3.7416573867739413

4.

In [44]:
a_1 = A[0] / np.linalg.norm(A)
a_2 = A[1] / np.linalg.norm(A)
a_3 = A[2] / np.linalg.norm(A)

print(f'Directions cosines for A: {a_1, a_2, a_3}')

Directions cosines for A: (array([0.26726124]), array([0.53452248]), array([0.80178373]))


5.

32

In [67]:
np.linalg.norm(B)

8.774964387392123

In [73]:
dot = np.sum(A*B)
norms = np.linalg.norm(A) * np.linalg.norm(B)

print(f'Angle between A and B in degrees: {np.rad2deg(np.arccos(np.clip(dot/norms, -1, 1)))}')

Angle between A and B in degrees: 12.933154491899135


6.

In [74]:
print(f'A•B: {np.dot(np.squeeze(A), np.squeeze(B))}\nB•A: {np.dot(np.squeeze(B), np.squeeze(A))}')

A•B: 32
B•A: 32


7.

In [76]:
costheta = dot/norms # from up above
print(f'A•B using angle between A and B: {np.linalg.norm(A) * np.linalg.norm(B) * costheta}')

A•B using angle between A and B: 32.0


8.

In [82]:
np.dot(np.squeeze(B), np.squeeze(A_hat)) / np.linalg.norm(A_hat)

8.55235974119758

9.

In [135]:
# To find a perpeinduclar vector just take the cross product
perp_vect = np.cross(np.squeeze(A), [1,0,0])
print(perp_vect)

#We can check and ensure it's perpendicular by taking the dot product
np.dot(np.squeeze(A), perp_vect)==0

[ 0  3 -2]


True

10.

In [85]:
print(f'AxB: {np.cross(np.squeeze(A), np.squeeze(B))}\nBxA: {np.cross(np.squeeze(B), np.squeeze(A))}')

AxB: [-3  6 -3]
BxA: [ 3 -6  3]


11.

In [141]:
# To find a vector that is perpendicular to both A and B we must
# Take the cross product of of Vectors A and B. The vector returned will be
# perpendicular to both A and B
perp_vector_AB = np.cross(np.squeeze(A), np.squeeze(B))
print(perp_vector_AB)

#Verify that this is indeed perpendicular to both A and B by taking the dot products
[np.dot(np.squeeze(A), perp_vector_AB)==0,
np.dot(np.squeeze(B), perp_vector_AB)==0]

[-3  6 -3]


[True, True]

12.

13.

In [126]:
print(f'ATb = {np.matmul(np.squeeze(A.T), np.squeeze(B))}')

#abT:
print(f'AbT = \n{np.matmul(A, B.T)}')

ATb = 32
AbT = 
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## Part B

In [154]:
A = np.array(([1,2,3], [4,-2,3], [0,5,-1]))
B = np.array(([1,2,1], [2,1,-4], [3,-2,1]))
C = np.array(([1,2,3], [4,5,6], [-1,1,3]))
D = np.array(([1,2,3]))
print(f'A: {A}\nShape: {np.shape(A)}\n')
print(f'B: {B}\nShape: {np.shape(B)}\n')
print(f'C: {C}\nShape: {np.shape(C)}\n')
print(f'D: {D}\nShape: {np.shape(D)}\n')

A: [[ 1  2  3]
 [ 4 -2  3]
 [ 0  5 -1]]
Shape: (3, 3)

B: [[ 1  2  1]
 [ 2  1 -4]
 [ 3 -2  1]]
Shape: (3, 3)

C: [[ 1  2  3]
 [ 4  5  6]
 [-1  1  3]]
Shape: (3, 3)

D: [1 2 3]
Shape: (3,)



1.

In [156]:
2*A - B

array([[ 1,  2,  5],
       [ 6, -5, 10],
       [-3, 12, -3]])

2.

In [161]:
print(f'AB: {np.matmul(A,B)}\n')
print(f'BA: {np.matmul(B,A)}')


AB: [[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]

BA: [[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


3.

In [163]:
print(f'(AB)T: {np.matmul(A,B).T}\n')
print(f'BTAT: {np.matmul(B.T, A.T)}')

(AB)T: [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]

BTAT: [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


4.

In [165]:
print(f'|A|: {np.linalg.det(A)}')
print(f'|C|: {np.linalg.det(C)}')

|A|: 54.999999999999964
|C|: 0.0


5.

In [175]:
np.shape(A)

(3, 3)

In [176]:
def orthogonal_set(A:np.ndarray, B:np.ndarray, C:np.ndarray) -> np.ndarray:
    '''This function will return the matrix of which the row vectors form an orthogonal set'''
    
    if np.dot(A[0], A[1]) == 0 or np.dot(A[0], A[2]) == 0 or np.dot(A[1], A[2]) == 0:
        return A
    elif np.dot(B[0], B[1]) == 0 or np.dot(B[0], B[2]) == 0 or np.dot(B[1], B[2]) == 0:
        return B
    elif np.dot(C[0], C[1]) == 0 or np.dot(C[0], C[2]) == 0 or np.dot(C[1], C[2]) == 0:
        return C
    

In [177]:
orthogonal_set(A, B, C)

array([[ 1,  2,  1],
       [ 2,  1, -4],
       [ 3, -2,  1]])

In [178]:
B

array([[ 1,  2,  1],
       [ 2,  1, -4],
       [ 3, -2,  1]])

Matrix B has orthogonal row vectors

6.

In [181]:
print(f'A^-1: {np.linalg.inv(A)}\n')
print(f'B^-1: {np.linalg.inv(B)}')

A^-1: [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]

B^-1: [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


7.

In [182]:
print(f'C^-1: {np.linalg.inv(C)}')

LinAlgError: Singular matrix

Since C is a singular matrix, there is no inverse.

8.

In [188]:
Ad = np.matmul(A,D)
print(Ad)

[14  9  7]


9.

In [234]:
normalized_D = D / np.linalg.norm(D)
normalized_D

array([0.26726124, 0.53452248, 0.80178373])

In [198]:
A_1 = A[0]
A_2 = A[1]
A_3 = A[2]

magnitude_D = (np.linalg.norm(D))**2

A_1d = np.dot(A_1, normalized_D)
A_2d = np.dot(A_2, normalized_D)
A_3d = np.dot(A_3, normalized_D)

Row 1, A

In [235]:
(A_1d / np.sqrt(magnitude_D))

3.7416573867739413

Row 2, A

In [236]:
(A_2d / np.sqrt(magnitude_D))

2.4053511772118195

Row 3, A

In [237]:
(A_3d / np.sqrt(magnitude_D))

1.8708286933869707

10.

In [233]:
normalized_D = D / np.linalg.norm(D)
normalized_D

array([0.26726124, 0.53452248, 0.80178373])

Row 1, A

In [229]:
(np.dot(A_1, normalized_D) / magnitude_D) * normalized_D

array([0.07142857, 0.14285714, 0.21428571])

Row 2, A

In [231]:
(np.dot(A_2, normalized_D) / magnitude_D) * normalized_D

array([0.04591837, 0.09183673, 0.1377551 ])

Row 3, A

In [232]:
(np.dot(A_3, normalized_D) / magnitude_D) * normalized_D

array([0.03571429, 0.07142857, 0.10714286])

11.

In [206]:
(A_1)*D[0] + (A_2)*D[1] + (A_3)*D[2]

array([ 9, 13,  6])

12.

Bx = D

In [219]:
x = np.matmul(np.linalg.inv(B), D)
print(f'X: {x}')

X: [ 1.00000000e+00  5.55111512e-17 -2.77555756e-17]


This is basically equivalent to [1 0 0] 

13.

In [220]:
np.matmul(np.linalg.inv(C), D)

LinAlgError: Singular matrix

There is no solution x to the equation Cx=D because the matrix C is singular and therefore cannot find the inverse for that matrix.

## Part C

1.

2.

3.

4.

5.

6.

7.