# CS 577 Homework 1
#### Anas Puthawala

In [1]:
import numpy as np
import scipy

## Part A

In [30]:
A = np.array([1,2,3])
A = np.reshape(A, newshape=(3,1))

B = np.reshape(np.array([4,5,6]), newshape=(3,1))

C = np.reshape(np.array([-1, 1, 3]), newshape=(3,1))

In [31]:
A

array([[1],
       [2],
       [3]])

In [32]:
B

array([[4],
       [5],
       [6]])

In [33]:
C

array([[-1],
       [ 1],
       [ 3]])

1.

In [37]:
2*A - B

array([[-2],
       [-1],
       [ 0]])

2.

In [79]:
A_hat = A / np.linalg.norm(A)
print(f'A_hat:\n{A_hat}')

A_hat:
[[0.26726124]
 [0.53452248]
 [0.80178373]]


3.

In [39]:
np.linalg.norm(A)

3.7416573867739413

4.

In [44]:
a_1 = A[0] / np.linalg.norm(A)
a_2 = A[1] / np.linalg.norm(A)
a_3 = A[2] / np.linalg.norm(A)

print(f'Directions cosines for A: {a_1, a_2, a_3}')

Directions cosines for A: (array([0.26726124]), array([0.53452248]), array([0.80178373]))


5.

32

In [67]:
np.linalg.norm(B)

8.774964387392123

In [73]:
dot = np.sum(A*B)
norms = np.linalg.norm(A) * np.linalg.norm(B)

print(f'Angle between A and B in degrees: {np.rad2deg(np.arccos(np.clip(dot/norms, -1, 1)))}')

Angle between A and B in degrees: 12.933154491899135


6.

In [74]:
print(f'A•B: {np.dot(np.squeeze(A), np.squeeze(B))}\nB•A: {np.dot(np.squeeze(B), np.squeeze(A))}')

A•B: 32
B•A: 32


7.

In [76]:
costheta = dot/norms # from up above
print(f'A•B using angle between A and B: {np.linalg.norm(A) * np.linalg.norm(B) * costheta}')

A•B using angle between A and B: 32.0


8.

In [82]:
np.dot(np.squeeze(B), np.squeeze(A_hat)) / np.linalg.norm(A_hat)

8.55235974119758

9.

In [135]:
# To find a perpeinduclar vector just take the cross product
perp_vect = np.cross(np.squeeze(A), [1,0,0])
print(perp_vect)

#We can check and ensure it's perpendicular by taking the dot product
np.dot(np.squeeze(A), perp_vect)==0

[ 0  3 -2]


True

10.

In [85]:
print(f'AxB: {np.cross(np.squeeze(A), np.squeeze(B))}\nBxA: {np.cross(np.squeeze(B), np.squeeze(A))}')

AxB: [-3  6 -3]
BxA: [ 3 -6  3]


11.

In [141]:
# To find a vector that is perpendicular to both A and B we must
# Take the cross product of of Vectors A and B. The vector returned will be
# perpendicular to both A and B
perp_vector_AB = np.cross(np.squeeze(A), np.squeeze(B))
print(perp_vector_AB)

#Verify that this is indeed perpendicular to both A and B by taking the dot products
[np.dot(np.squeeze(A), perp_vector_AB)==0,
np.dot(np.squeeze(B), perp_vector_AB)==0]

[-3  6 -3]


[True, True]

12.

13.

In [126]:
print(f'ATb = {np.matmul(np.squeeze(A.T), np.squeeze(B))}')

#abT:
print(f'AbT = \n{np.matmul(A, B.T)}')

ATb = 32
AbT = 
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## Part B

1.

2.

3.

4.

5.

6.

7.

8.

9.

10.

11.

12.

13.

## Part C

1.

2.

3.

4.

5.

6.

7.